-- Issue#135 Phase 3: 初期キーワード語彙の投入
--
-- AWS Rekognition のラベルから Photlas 向けに選別した約 200 個のキーワード。
-- 各キーワードには 5 言語 (日本語・英語・中国語簡体・韓国語・スペイン語) の表示名と、
-- 該当するカテゴリ（200番台）への紐付けを与える。
--
-- 翻訳方針 (Issue#135 3.3):
--   - 日本語・英語は監修品質を目指す
--   - 中国語（簡体）・韓国語・スペイン語は機械翻訳ベースの一次案として登録
--     （将来 scripts/translate-tags.ts 経由で改善可能）
--
-- カテゴリ紐付け (Issue#135 3.1):
--   - 多対多: 1 つのキーワードが複数のカテゴリに属し得る
--   - Bird 系は 207 (動物) + 208 (野鳥) の二重所属
--
-- 既存の Issue#132 CategoryDictionary との整合性 (Issue#135 3.2):
--   - 同一 Rekognition ラベルは同じ Photlas カテゴリへマッピングされる
--   - tag_categories はカテゴリ判定の DB 表現として機能

-- ========================================================================
-- tags: 約 207 件
-- ========================================================================
INSERT INTO tags
  (rekognition_label, slug, display_name_ja, display_name_en, display_name_zh, display_name_ko, display_name_es, sort_order)
VALUES
  -- 自然風景 (201) — 30 件
  ('Mountain', 'mountain', '山', 'Mountain', '山', '산', 'Montaña', 100),
  ('Sea', 'sea', '海', 'Sea', '海', '바다', 'Mar', 100),
  ('River', 'river', '川', 'River', '河流', '강', 'Río', 100),
  ('Forest', 'forest', '森', 'Forest', '森林', '숲', 'Bosque', 100),
  ('Landscape', 'landscape', '風景', 'Landscape', '风景', '풍경', 'Paisaje', 100),
  ('Waterfall', 'waterfall', '滝', 'Waterfall', '瀑布', '폭포', 'Cascada', 100),
  ('Cliff', 'cliff', '崖', 'Cliff', '悬崖', '절벽', 'Acantilado', 100),
  ('Beach', 'beach', '砂浜', 'Beach', '海滩', '해변', 'Playa', 100),
  ('Valley', 'valley', '谷', 'Valley', '山谷', '계곡', 'Valle', 100),
  ('Lake', 'lake', '湖', 'Lake', '湖', '호수', 'Lago', 100),
  ('Coast', 'coast', '海岸', 'Coast', '海岸', '해안', 'Costa', 100),
  ('Pond', 'pond', '池', 'Pond', '池塘', '연못', 'Estanque', 100),
  ('Glacier', 'glacier', '氷河', 'Glacier', '冰川', '빙하', 'Glaciar', 100),
  ('Canyon', 'canyon', '峡谷', 'Canyon', '峡谷', '협곡', 'Cañón', 100),
  ('Desert', 'desert', '砂漠', 'Desert', '沙漠', '사막', 'Desierto', 100),
  ('Hill', 'hill', '丘', 'Hill', '山丘', '언덕', 'Colina', 100),
  ('Stream', 'stream', '小川', 'Stream', '小溪', '시내', 'Arroyo', 100),
  ('Volcano', 'volcano', '火山', 'Volcano', '火山', '화산', 'Volcán', 100),
  ('Cave', 'cave', '洞窟', 'Cave', '洞穴', '동굴', 'Cueva', 100),
  ('Rainbow', 'rainbow', '虹', 'Rainbow', '彩虹', '무지개', 'Arcoíris', 100),
  ('Sunset', 'sunset', '夕日', 'Sunset', '日落', '일몰', 'Atardecer', 100),
  ('Sunrise', 'sunrise', '朝日', 'Sunrise', '日出', '일출', 'Amanecer', 100),
  ('Dawn', 'dawn', '夜明け', 'Dawn', '黎明', '새벽', 'Madrugada', 100),
  ('Dusk', 'dusk', '黄昏', 'Dusk', '黄昏', '황혼', 'Crepúsculo', 100),
  ('Island', 'island', '島', 'Island', '岛屿', '섬', 'Isla', 100),
  ('Bay', 'bay', '湾', 'Bay', '海湾', '만', 'Bahía', 100),
  ('Ocean', 'ocean', '大洋', 'Ocean', '大海', '대양', 'Océano', 100),
  ('Peak', 'peak', '山頂', 'Peak', '山顶', '정상', 'Cima', 100),
  ('Dune', 'dune', '砂丘', 'Dune', '沙丘', '사구', 'Duna', 100),
  ('Meadow', 'meadow', '草原', 'Meadow', '草地', '초원', 'Pradera', 100),

  -- 街並み (202) — 12 件
  ('City', 'city', '街', 'City', '城市', '도시', 'Ciudad', 100),
  ('Skyline', 'skyline', 'スカイライン', 'Skyline', '天际线', '스카이라인', 'Horizonte urbano', 100),
  ('Urban', 'urban', '都会', 'Urban', '都市', '도시의', 'Urbano', 100),
  ('Cityscape', 'cityscape', '街並み', 'Cityscape', '城市景观', '도시 풍경', 'Paisaje urbano', 100),
  ('Downtown', 'downtown', '繁華街', 'Downtown', '市中心', '다운타운', 'Centro', 100),
  ('Town', 'town', '町', 'Town', '城镇', '마을', 'Pueblo', 100),
  ('Metropolis', 'metropolis', 'メトロポリス', 'Metropolis', '大都市', '메트로폴리스', 'Metrópoli', 100),
  ('Neighborhood', 'neighborhood', '住宅街', 'Neighborhood', '邻里', '동네', 'Vecindario', 100),
  ('Street', 'street', '通り', 'Street', '街道', '거리', 'Calle', 100),
  ('Avenue', 'avenue', '大通り', 'Avenue', '大道', '대로', 'Avenida', 100),
  ('Alley', 'alley', '路地', 'Alley', '巷子', '골목', 'Callejón', 100),
  ('Plaza', 'plaza', '広場', 'Plaza', '广场', '광장', 'Plaza', 100),

  -- 建造物 (203) — 25 件
  ('Building', 'building', '建物', 'Building', '建筑', '건물', 'Edificio', 100),
  ('Architecture', 'architecture', '建築', 'Architecture', '建筑', '건축', 'Arquitectura', 100),
  ('Bridge', 'bridge', '橋', 'Bridge', '桥', '다리', 'Puente', 100),
  ('Tower', 'tower', '塔', 'Tower', '塔', '탑', 'Torre', 100),
  ('Skyscraper', 'skyscraper', '高層ビル', 'Skyscraper', '摩天大楼', '마천루', 'Rascacielos', 100),
  ('Castle', 'castle', '城', 'Castle', '城堡', '성', 'Castillo', 100),
  ('Temple', 'temple', '寺', 'Temple', '寺庙', '사원', 'Templo', 100),
  ('Shrine', 'shrine', '神社', 'Shrine', '神社', '신사', 'Santuario', 100),
  ('Church', 'church', '教会', 'Church', '教堂', '교회', 'Iglesia', 100),
  ('Cathedral', 'cathedral', '大聖堂', 'Cathedral', '大教堂', '대성당', 'Catedral', 100),
  ('Mosque', 'mosque', 'モスク', 'Mosque', '清真寺', '모스크', 'Mezquita', 100),
  ('Pagoda', 'pagoda', '五重塔', 'Pagoda', '宝塔', '오층탑', 'Pagoda', 100),
  ('Pyramid', 'pyramid', 'ピラミッド', 'Pyramid', '金字塔', '피라미드', 'Pirámide', 100),
  ('Monument', 'monument', '記念碑', 'Monument', '纪念碑', '기념비', 'Monumento', 100),
  ('Fortress', 'fortress', '要塞', 'Fortress', '要塞', '요새', 'Fortaleza', 100),
  ('Tunnel', 'tunnel', 'トンネル', 'Tunnel', '隧道', '터널', 'Túnel', 100),
  ('Lighthouse', 'lighthouse', '灯台', 'Lighthouse', '灯塔', '등대', 'Faro', 100),
  ('Stadium', 'stadium', 'スタジアム', 'Stadium', '体育场', '경기장', 'Estadio', 100),
  ('Arena', 'arena', 'アリーナ', 'Arena', '竞技场', '아레나', 'Arena', 100),
  ('Dam', 'dam', 'ダム', 'Dam', '水坝', '댐', 'Presa', 100),
  ('Pier', 'pier', '桟橋', 'Pier', '码头', '부두', 'Muelle', 100),
  ('Pavilion', 'pavilion', 'パビリオン', 'Pavilion', '亭子', '정자', 'Pabellón', 100),
  ('Hotel', 'hotel', 'ホテル', 'Hotel', '酒店', '호텔', 'Hotel', 100),
  ('Torii', 'torii', '鳥居', 'Torii', '鸟居', '도리이', 'Torii', 100),
  ('Gate', 'gate', '門', 'Gate', '大门', '문', 'Puerta', 100),

  -- 夜景 (204) — 4 件
  ('Lighting', 'lighting', 'ライティング', 'Lighting', '灯光', '조명', 'Iluminación', 100),
  ('Illumination', 'illumination', 'イルミネーション', 'Illumination', '灯饰', '일루미네이션', 'Alumbrado', 100),
  ('Nightlife', 'nightlife', 'ナイトライフ', 'Nightlife', '夜生活', '나이트라이프', 'Vida nocturna', 100),
  ('Neon', 'neon', 'ネオン', 'Neon', '霓虹', '네온', 'Neón', 100),

  -- グルメ (205) — 35 件
  ('Food', 'food', '食事', 'Food', '食物', '음식', 'Comida', 100),
  ('Restaurant', 'restaurant', 'レストラン', 'Restaurant', '餐厅', '레스토랑', 'Restaurante', 100),
  ('Cuisine', 'cuisine', '料理', 'Cuisine', '美食', '요리', 'Cocina', 100),
  ('Bread', 'bread', 'パン', 'Bread', '面包', '빵', 'Pan', 100),
  ('Cake', 'cake', 'ケーキ', 'Cake', '蛋糕', '케이크', 'Pastel', 100),
  ('Coffee', 'coffee', 'コーヒー', 'Coffee', '咖啡', '커피', 'Café', 100),
  ('Sushi', 'sushi', '寿司', 'Sushi', '寿司', '스시', 'Sushi', 100),
  ('Ramen', 'ramen', 'ラーメン', 'Ramen', '拉面', '라멘', 'Ramen', 100),
  ('Dessert', 'dessert', 'デザート', 'Dessert', '甜点', '디저트', 'Postre', 100),
  ('Beverage', 'beverage', '飲み物', 'Beverage', '饮料', '음료', 'Bebida', 100),
  ('Fruit', 'fruit', '果物', 'Fruit', '水果', '과일', 'Fruta', 100),
  ('Vegetable', 'vegetable', '野菜', 'Vegetable', '蔬菜', '채소', 'Verdura', 100),
  ('Pasta', 'pasta', 'パスタ', 'Pasta', '意大利面', '파스타', 'Pasta', 100),
  ('Pizza', 'pizza', 'ピザ', 'Pizza', '披萨', '피자', 'Pizza', 100),
  ('Sandwich', 'sandwich', 'サンドイッチ', 'Sandwich', '三明治', '샌드위치', 'Sándwich', 100),
  ('Burger', 'burger', 'バーガー', 'Burger', '汉堡', '버거', 'Hamburguesa', 100),
  ('Donut', 'donut', 'ドーナツ', 'Donut', '甜甜圈', '도넛', 'Dona', 100),
  ('Cookie', 'cookie', 'クッキー', 'Cookie', '饼干', '쿠키', 'Galleta', 100),
  ('Pancake', 'pancake', 'パンケーキ', 'Pancake', '薄煎饼', '팬케이크', 'Panqueque', 100),
  ('Salad', 'salad', 'サラダ', 'Salad', '沙拉', '샐러드', 'Ensalada', 100),
  ('Soup', 'soup', 'スープ', 'Soup', '汤', '수프', 'Sopa', 100),
  ('Curry', 'curry', 'カレー', 'Curry', '咖喱', '카레', 'Curry', 100),
  ('Noodle', 'noodle', '麺', 'Noodle', '面条', '면', 'Fideos', 100),
  ('Cheese', 'cheese', 'チーズ', 'Cheese', '奶酪', '치즈', 'Queso', 100),
  ('Wine', 'wine', 'ワイン', 'Wine', '葡萄酒', '와인', 'Vino', 100),
  ('Beer', 'beer', 'ビール', 'Beer', '啤酒', '맥주', 'Cerveza', 100),
  ('Cocktail', 'cocktail', 'カクテル', 'Cocktail', '鸡尾酒', '칵테일', 'Cóctel', 100),
  ('Tea', 'tea', 'お茶', 'Tea', '茶', '차', 'Té', 100),
  ('Ice Cream', 'ice-cream', 'アイスクリーム', 'Ice Cream', '冰淇淋', '아이스크림', 'Helado', 100),
  ('Chocolate', 'chocolate', 'チョコレート', 'Chocolate', '巧克力', '초콜릿', 'Chocolate', 100),
  ('Steak', 'steak', 'ステーキ', 'Steak', '牛排', '스테이크', 'Bistec', 100),
  ('Seafood', 'seafood', '海鮮', 'Seafood', '海鲜', '해산물', 'Mariscos', 100),
  ('Cafe', 'cafe', 'カフェ', 'Cafe', '咖啡馆', '카페', 'Café', 100),
  ('Bakery', 'bakery', 'ベーカリー', 'Bakery', '面包店', '베이커리', 'Panadería', 100),
  ('Breakfast', 'breakfast', '朝食', 'Breakfast', '早餐', '아침 식사', 'Desayuno', 100),

  -- 植物 (206) — 25 件
  ('Flower', 'flower', '花', 'Flower', '花', '꽃', 'Flor', 100),
  ('Plant', 'plant', '植物', 'Plant', '植物', '식물', 'Planta', 100),
  ('Tree', 'tree', '木', 'Tree', '树', '나무', 'Árbol', 100),
  ('Garden', 'garden', '庭園', 'Garden', '花园', '정원', 'Jardín', 100),
  ('Leaf', 'leaf', '葉', 'Leaf', '叶子', '잎', 'Hoja', 100),
  ('Petal', 'petal', '花びら', 'Petal', '花瓣', '꽃잎', 'Pétalo', 100),
  ('Vegetation', 'vegetation', '草木', 'Vegetation', '植被', '식생', 'Vegetación', 100),
  ('Moss', 'moss', '苔', 'Moss', '苔藓', '이끼', 'Musgo', 100),
  ('Bush', 'bush', '茂み', 'Bush', '灌木', '덤불', 'Arbusto', 100),
  ('Vineyard', 'vineyard', 'ぶどう畑', 'Vineyard', '葡萄园', '포도원', 'Viñedo', 100),
  ('Grass', 'grass', '草', 'Grass', '草', '풀', 'Hierba', 100),
  ('Lawn', 'lawn', '芝生', 'Lawn', '草坪', '잔디', 'Césped', 100),
  ('Blossom', 'blossom', '花房', 'Blossom', '花朵', '꽃', 'Flor', 100),
  ('Rose', 'rose', 'バラ', 'Rose', '玫瑰', '장미', 'Rosa', 100),
  ('Tulip', 'tulip', 'チューリップ', 'Tulip', '郁金香', '튤립', 'Tulipán', 100),
  ('Cherry Blossom', 'cherry-blossom', '桜', 'Cherry Blossom', '樱花', '벚꽃', 'Flor de cerezo', 100),
  ('Sunflower', 'sunflower', 'ひまわり', 'Sunflower', '向日葵', '해바라기', 'Girasol', 100),
  ('Lily', 'lily', '百合', 'Lily', '百合', '백합', 'Lirio', 100),
  ('Orchid', 'orchid', '蘭', 'Orchid', '兰花', '난초', 'Orquídea', 100),
  ('Lavender', 'lavender', 'ラベンダー', 'Lavender', '薰衣草', '라벤더', 'Lavanda', 100),
  ('Cactus', 'cactus', 'サボテン', 'Cactus', '仙人掌', '선인장', 'Cactus', 100),
  ('Bamboo', 'bamboo', '竹', 'Bamboo', '竹子', '대나무', 'Bambú', 100),
  ('Fern', 'fern', 'シダ', 'Fern', '蕨类', '양치류', 'Helecho', 100),
  ('Maple', 'maple', 'もみじ', 'Maple', '枫树', '단풍나무', 'Arce', 100),
  ('Foliage', 'foliage', '紅葉', 'Foliage', '红叶', '단풍', 'Follaje', 100),

  -- 動物 (207) — 25 件
  ('Animal', 'animal', '動物', 'Animal', '动物', '동물', 'Animal', 100),
  ('Dog', 'dog', '犬', 'Dog', '狗', '개', 'Perro', 100),
  ('Cat', 'cat', '猫', 'Cat', '猫', '고양이', 'Gato', 100),
  ('Mammal', 'mammal', '哺乳類', 'Mammal', '哺乳动物', '포유류', 'Mamífero', 100),
  ('Wildlife', 'wildlife', '野生動物', 'Wildlife', '野生动物', '야생 동물', 'Vida salvaje', 100),
  ('Pet', 'pet', 'ペット', 'Pet', '宠物', '반려동물', 'Mascota', 100),
  ('Fox', 'fox', 'キツネ', 'Fox', '狐狸', '여우', 'Zorro', 100),
  ('Bear', 'bear', 'クマ', 'Bear', '熊', '곰', 'Oso', 100),
  ('Deer', 'deer', 'シカ', 'Deer', '鹿', '사슴', 'Ciervo', 100),
  ('Squirrel', 'squirrel', 'リス', 'Squirrel', '松鼠', '다람쥐', 'Ardilla', 100),
  ('Rabbit', 'rabbit', 'ウサギ', 'Rabbit', '兔子', '토끼', 'Conejo', 100),
  ('Lion', 'lion', 'ライオン', 'Lion', '狮子', '사자', 'León', 100),
  ('Tiger', 'tiger', 'トラ', 'Tiger', '老虎', '호랑이', 'Tigre', 100),
  ('Elephant', 'elephant', 'ゾウ', 'Elephant', '大象', '코끼리', 'Elefante', 100),
  ('Giraffe', 'giraffe', 'キリン', 'Giraffe', '长颈鹿', '기린', 'Jirafa', 100),
  ('Zebra', 'zebra', 'シマウマ', 'Zebra', '斑马', '얼룩말', 'Cebra', 100),
  ('Horse', 'horse', '馬', 'Horse', '马', '말', 'Caballo', 100),
  ('Cow', 'cow', '牛', 'Cow', '牛', '소', 'Vaca', 100),
  ('Sheep', 'sheep', '羊', 'Sheep', '羊', '양', 'Oveja', 100),
  ('Monkey', 'monkey', 'サル', 'Monkey', '猴子', '원숭이', 'Mono', 100),
  ('Wolf', 'wolf', 'オオカミ', 'Wolf', '狼', '늑대', 'Lobo', 100),
  ('Panda', 'panda', 'パンダ', 'Panda', '熊猫', '판다', 'Panda', 100),
  ('Whale', 'whale', 'クジラ', 'Whale', '鲸鱼', '고래', 'Ballena', 100),
  ('Dolphin', 'dolphin', 'イルカ', 'Dolphin', '海豚', '돌고래', 'Delfín', 100),
  ('Butterfly', 'butterfly', '蝶', 'Butterfly', '蝴蝶', '나비', 'Mariposa', 100),

  -- 野鳥 (208) + 動物 (207) 二重所属 — 16 件
  ('Bird', 'bird', '鳥', 'Bird', '鸟', '새', 'Pájaro', 100),
  ('Sparrow', 'sparrow', 'スズメ', 'Sparrow', '麻雀', '참새', 'Gorrión', 100),
  ('Eagle', 'eagle', '鷲', 'Eagle', '鹰', '독수리', 'Águila', 100),
  ('Hawk', 'hawk', 'タカ', 'Hawk', '鹰', '매', 'Halcón', 100),
  ('Owl', 'owl', 'フクロウ', 'Owl', '猫头鹰', '부엉이', 'Búho', 100),
  ('Crow', 'crow', 'カラス', 'Crow', '乌鸦', '까마귀', 'Cuervo', 100),
  ('Heron', 'heron', 'サギ', 'Heron', '苍鹭', '왜가리', 'Garza', 100),
  ('Crane', 'crane', '鶴', 'Crane', '鹤', '학', 'Grulla', 100),
  ('Swan', 'swan', '白鳥', 'Swan', '天鹅', '백조', 'Cisne', 100),
  ('Goose', 'goose', 'ガチョウ', 'Goose', '鹅', '거위', 'Ganso', 100),
  ('Duck', 'duck', 'カモ', 'Duck', '鸭子', '오리', 'Pato', 100),
  ('Seagull', 'seagull', 'カモメ', 'Seagull', '海鸥', '갈매기', 'Gaviota', 100),
  ('Penguin', 'penguin', 'ペンギン', 'Penguin', '企鹅', '펭귄', 'Pingüino', 100),
  ('Flamingo', 'flamingo', 'フラミンゴ', 'Flamingo', '火烈鸟', '플라밍고', 'Flamenco', 100),
  ('Falcon', 'falcon', 'ハヤブサ', 'Falcon', '隼', '송골매', 'Halcón peregrino', 100),
  ('Kingfisher', 'kingfisher', 'カワセミ', 'Kingfisher', '翠鸟', '물총새', 'Martín pescador', 100),

  -- 自動車 (209) — 10 件
  ('Car', 'car', '自動車', 'Car', '汽车', '자동차', 'Coche', 100),
  ('Vehicle', 'vehicle', '乗り物', 'Vehicle', '车辆', '차량', 'Vehículo', 100),
  ('Sedan', 'sedan', 'セダン', 'Sedan', '轿车', '세단', 'Sedán', 100),
  ('Suv', 'suv', 'SUV', 'SUV', 'SUV', 'SUV', 'SUV', 100),
  ('Truck', 'truck', 'トラック', 'Truck', '卡车', '트럭', 'Camión', 100),
  ('Sports Car', 'sports-car', 'スポーツカー', 'Sports Car', '跑车', '스포츠카', 'Coche deportivo', 100),
  ('Convertible', 'convertible', 'オープンカー', 'Convertible', '敞篷车', '컨버터블', 'Descapotable', 100),
  ('Bus', 'bus', 'バス', 'Bus', '公交车', '버스', 'Autobús', 100),
  ('Taxi', 'taxi', 'タクシー', 'Taxi', '出租车', '택시', 'Taxi', 100),
  ('Pickup Truck', 'pickup-truck', 'ピックアップトラック', 'Pickup Truck', '皮卡', '픽업트럭', 'Camioneta', 100),

  -- バイク (210) — 3 件
  ('Motorcycle', 'motorcycle', 'バイク', 'Motorcycle', '摩托车', '오토바이', 'Motocicleta', 100),
  ('Scooter', 'scooter', 'スクーター', 'Scooter', '小型摩托车', '스쿠터', 'Escúter', 100),
  ('Moped', 'moped', 'モペッド', 'Moped', '助力车', '모페드', 'Ciclomotor', 100),

  -- 鉄道 (211) — 8 件
  ('Train', 'train', '列車', 'Train', '火车', '기차', 'Tren', 100),
  ('Railway', 'railway', '鉄道', 'Railway', '铁路', '철도', 'Ferrocarril', 100),
  ('Locomotive', 'locomotive', '機関車', 'Locomotive', '机车', '기관차', 'Locomotora', 100),
  ('Subway', 'subway', '地下鉄', 'Subway', '地铁', '지하철', 'Metro', 100),
  ('Tram', 'tram', '路面電車', 'Tram', '有轨电车', '트램', 'Tranvía', 100),
  ('Cable Car', 'cable-car', 'ケーブルカー', 'Cable Car', '缆车', '케이블카', 'Funicular', 100),
  ('Monorail', 'monorail', 'モノレール', 'Monorail', '单轨', '모노레일', 'Monorraíl', 100),
  ('Bullet Train', 'bullet-train', '新幹線', 'Bullet Train', '高铁', '신칸센', 'Tren bala', 100),

  -- 飛行機 (212) — 6 件
  ('Aircraft', 'aircraft', '航空機', 'Aircraft', '飞机', '항공기', 'Aeronave', 100),
  ('Airplane', 'airplane', '飛行機', 'Airplane', '飞机', '비행기', 'Avión', 100),
  ('Helicopter', 'helicopter', 'ヘリコプター', 'Helicopter', '直升机', '헬리콥터', 'Helicóptero', 100),
  ('Jet', 'jet', 'ジェット機', 'Jet', '喷气机', '제트기', 'Jet', 100),
  ('Airliner', 'airliner', '旅客機', 'Airliner', '客机', '여객기', 'Avión de pasajeros', 100),
  ('Glider', 'glider', 'グライダー', 'Glider', '滑翔机', '글라이더', 'Planeador', 100),

  -- 星空 (213) — 8 件
  ('Star', 'star', '星', 'Star', '星', '별', 'Estrella', 100),
  ('Night Sky', 'night-sky', '夜空', 'Night Sky', '夜空', '밤하늘', 'Cielo nocturno', 100),
  ('Milky Way', 'milky-way', '天の川', 'Milky Way', '银河', '은하수', 'Vía Láctea', 100),
  ('Galaxy', 'galaxy', '銀河', 'Galaxy', '银河系', '은하', 'Galaxia', 100),
  ('Constellation', 'constellation', '星座', 'Constellation', '星座', '별자리', 'Constelación', 100),
  ('Nebula', 'nebula', '星雲', 'Nebula', '星云', '성운', 'Nebulosa', 100),
  ('Astronomy', 'astronomy', '天文', 'Astronomy', '天文', '천문', 'Astronomía', 100),
  ('Aurora', 'aurora', 'オーロラ', 'Aurora', '极光', '오로라', 'Aurora', 100)
;

-- ========================================================================
-- tag_categories: 各 tag に該当カテゴリを紐付け（多対多）
-- ========================================================================
INSERT INTO tag_categories (tag_id, category_code) VALUES
  -- 自然風景 (201)
  ((SELECT id FROM tags WHERE slug='mountain'), 201),
  ((SELECT id FROM tags WHERE slug='sea'), 201),
  ((SELECT id FROM tags WHERE slug='river'), 201),
  ((SELECT id FROM tags WHERE slug='forest'), 201),
  ((SELECT id FROM tags WHERE slug='landscape'), 201),
  ((SELECT id FROM tags WHERE slug='waterfall'), 201),
  ((SELECT id FROM tags WHERE slug='cliff'), 201),
  ((SELECT id FROM tags WHERE slug='beach'), 201),
  ((SELECT id FROM tags WHERE slug='valley'), 201),
  ((SELECT id FROM tags WHERE slug='lake'), 201),
  ((SELECT id FROM tags WHERE slug='coast'), 201),
  ((SELECT id FROM tags WHERE slug='pond'), 201),
  ((SELECT id FROM tags WHERE slug='glacier'), 201),
  ((SELECT id FROM tags WHERE slug='canyon'), 201),
  ((SELECT id FROM tags WHERE slug='desert'), 201),
  ((SELECT id FROM tags WHERE slug='hill'), 201),
  ((SELECT id FROM tags WHERE slug='stream'), 201),
  ((SELECT id FROM tags WHERE slug='volcano'), 201),
  ((SELECT id FROM tags WHERE slug='cave'), 201),
  ((SELECT id FROM tags WHERE slug='rainbow'), 201),
  ((SELECT id FROM tags WHERE slug='sunset'), 201),
  ((SELECT id FROM tags WHERE slug='sunrise'), 201),
  ((SELECT id FROM tags WHERE slug='dawn'), 201),
  ((SELECT id FROM tags WHERE slug='dusk'), 201),
  ((SELECT id FROM tags WHERE slug='island'), 201),
  ((SELECT id FROM tags WHERE slug='bay'), 201),
  ((SELECT id FROM tags WHERE slug='ocean'), 201),
  ((SELECT id FROM tags WHERE slug='peak'), 201),
  ((SELECT id FROM tags WHERE slug='dune'), 201),
  ((SELECT id FROM tags WHERE slug='meadow'), 201),

  -- 街並み (202)
  ((SELECT id FROM tags WHERE slug='city'), 202),
  ((SELECT id FROM tags WHERE slug='skyline'), 202),
  ((SELECT id FROM tags WHERE slug='urban'), 202),
  ((SELECT id FROM tags WHERE slug='cityscape'), 202),
  ((SELECT id FROM tags WHERE slug='downtown'), 202),
  ((SELECT id FROM tags WHERE slug='town'), 202),
  ((SELECT id FROM tags WHERE slug='metropolis'), 202),
  ((SELECT id FROM tags WHERE slug='neighborhood'), 202),
  ((SELECT id FROM tags WHERE slug='street'), 202),
  ((SELECT id FROM tags WHERE slug='avenue'), 202),
  ((SELECT id FROM tags WHERE slug='alley'), 202),
  ((SELECT id FROM tags WHERE slug='plaza'), 202),

  -- 建造物 (203)
  ((SELECT id FROM tags WHERE slug='building'), 203),
  ((SELECT id FROM tags WHERE slug='architecture'), 203),
  ((SELECT id FROM tags WHERE slug='bridge'), 203),
  ((SELECT id FROM tags WHERE slug='tower'), 203),
  ((SELECT id FROM tags WHERE slug='skyscraper'), 203),
  ((SELECT id FROM tags WHERE slug='castle'), 203),
  ((SELECT id FROM tags WHERE slug='temple'), 203),
  ((SELECT id FROM tags WHERE slug='shrine'), 203),
  ((SELECT id FROM tags WHERE slug='church'), 203),
  ((SELECT id FROM tags WHERE slug='cathedral'), 203),
  ((SELECT id FROM tags WHERE slug='mosque'), 203),
  ((SELECT id FROM tags WHERE slug='pagoda'), 203),
  ((SELECT id FROM tags WHERE slug='pyramid'), 203),
  ((SELECT id FROM tags WHERE slug='monument'), 203),
  ((SELECT id FROM tags WHERE slug='fortress'), 203),
  ((SELECT id FROM tags WHERE slug='tunnel'), 203),
  ((SELECT id FROM tags WHERE slug='lighthouse'), 203),
  ((SELECT id FROM tags WHERE slug='stadium'), 203),
  ((SELECT id FROM tags WHERE slug='arena'), 203),
  ((SELECT id FROM tags WHERE slug='dam'), 203),
  ((SELECT id FROM tags WHERE slug='pier'), 203),
  ((SELECT id FROM tags WHERE slug='pavilion'), 203),
  ((SELECT id FROM tags WHERE slug='hotel'), 203),
  ((SELECT id FROM tags WHERE slug='torii'), 203),
  ((SELECT id FROM tags WHERE slug='gate'), 203),

  -- 夜景 (204)
  ((SELECT id FROM tags WHERE slug='lighting'), 204),
  ((SELECT id FROM tags WHERE slug='illumination'), 204),
  ((SELECT id FROM tags WHERE slug='nightlife'), 204),
  ((SELECT id FROM tags WHERE slug='neon'), 204),

  -- グルメ (205)
  ((SELECT id FROM tags WHERE slug='food'), 205),
  ((SELECT id FROM tags WHERE slug='restaurant'), 205),
  ((SELECT id FROM tags WHERE slug='cuisine'), 205),
  ((SELECT id FROM tags WHERE slug='bread'), 205),
  ((SELECT id FROM tags WHERE slug='cake'), 205),
  ((SELECT id FROM tags WHERE slug='coffee'), 205),
  ((SELECT id FROM tags WHERE slug='sushi'), 205),
  ((SELECT id FROM tags WHERE slug='ramen'), 205),
  ((SELECT id FROM tags WHERE slug='dessert'), 205),
  ((SELECT id FROM tags WHERE slug='beverage'), 205),
  ((SELECT id FROM tags WHERE slug='fruit'), 205),
  ((SELECT id FROM tags WHERE slug='vegetable'), 205),
  ((SELECT id FROM tags WHERE slug='pasta'), 205),
  ((SELECT id FROM tags WHERE slug='pizza'), 205),
  ((SELECT id FROM tags WHERE slug='sandwich'), 205),
  ((SELECT id FROM tags WHERE slug='burger'), 205),
  ((SELECT id FROM tags WHERE slug='donut'), 205),
  ((SELECT id FROM tags WHERE slug='cookie'), 205),
  ((SELECT id FROM tags WHERE slug='pancake'), 205),
  ((SELECT id FROM tags WHERE slug='salad'), 205),
  ((SELECT id FROM tags WHERE slug='soup'), 205),
  ((SELECT id FROM tags WHERE slug='curry'), 205),
  ((SELECT id FROM tags WHERE slug='noodle'), 205),
  ((SELECT id FROM tags WHERE slug='cheese'), 205),
  ((SELECT id FROM tags WHERE slug='wine'), 205),
  ((SELECT id FROM tags WHERE slug='beer'), 205),
  ((SELECT id FROM tags WHERE slug='cocktail'), 205),
  ((SELECT id FROM tags WHERE slug='tea'), 205),
  ((SELECT id FROM tags WHERE slug='ice-cream'), 205),
  ((SELECT id FROM tags WHERE slug='chocolate'), 205),
  ((SELECT id FROM tags WHERE slug='steak'), 205),
  ((SELECT id FROM tags WHERE slug='seafood'), 205),
  ((SELECT id FROM tags WHERE slug='cafe'), 205),
  ((SELECT id FROM tags WHERE slug='bakery'), 205),
  ((SELECT id FROM tags WHERE slug='breakfast'), 205),

  -- 植物 (206)
  ((SELECT id FROM tags WHERE slug='flower'), 206),
  ((SELECT id FROM tags WHERE slug='plant'), 206),
  ((SELECT id FROM tags WHERE slug='tree'), 206),
  ((SELECT id FROM tags WHERE slug='garden'), 206),
  ((SELECT id FROM tags WHERE slug='leaf'), 206),
  ((SELECT id FROM tags WHERE slug='petal'), 206),
  ((SELECT id FROM tags WHERE slug='vegetation'), 206),
  ((SELECT id FROM tags WHERE slug='moss'), 206),
  ((SELECT id FROM tags WHERE slug='bush'), 206),
  ((SELECT id FROM tags WHERE slug='vineyard'), 206),
  ((SELECT id FROM tags WHERE slug='grass'), 206),
  ((SELECT id FROM tags WHERE slug='lawn'), 206),
  ((SELECT id FROM tags WHERE slug='blossom'), 206),
  ((SELECT id FROM tags WHERE slug='rose'), 206),
  ((SELECT id FROM tags WHERE slug='tulip'), 206),
  ((SELECT id FROM tags WHERE slug='cherry-blossom'), 206),
  ((SELECT id FROM tags WHERE slug='sunflower'), 206),
  ((SELECT id FROM tags WHERE slug='lily'), 206),
  ((SELECT id FROM tags WHERE slug='orchid'), 206),
  ((SELECT id FROM tags WHERE slug='lavender'), 206),
  ((SELECT id FROM tags WHERE slug='cactus'), 206),
  ((SELECT id FROM tags WHERE slug='bamboo'), 206),
  ((SELECT id FROM tags WHERE slug='fern'), 206),
  ((SELECT id FROM tags WHERE slug='maple'), 206),
  ((SELECT id FROM tags WHERE slug='foliage'), 206),

  -- 動物 (207)
  ((SELECT id FROM tags WHERE slug='animal'), 207),
  ((SELECT id FROM tags WHERE slug='dog'), 207),
  ((SELECT id FROM tags WHERE slug='cat'), 207),
  ((SELECT id FROM tags WHERE slug='mammal'), 207),
  ((SELECT id FROM tags WHERE slug='wildlife'), 207),
  ((SELECT id FROM tags WHERE slug='pet'), 207),
  ((SELECT id FROM tags WHERE slug='fox'), 207),
  ((SELECT id FROM tags WHERE slug='bear'), 207),
  ((SELECT id FROM tags WHERE slug='deer'), 207),
  ((SELECT id FROM tags WHERE slug='squirrel'), 207),
  ((SELECT id FROM tags WHERE slug='rabbit'), 207),
  ((SELECT id FROM tags WHERE slug='lion'), 207),
  ((SELECT id FROM tags WHERE slug='tiger'), 207),
  ((SELECT id FROM tags WHERE slug='elephant'), 207),
  ((SELECT id FROM tags WHERE slug='giraffe'), 207),
  ((SELECT id FROM tags WHERE slug='zebra'), 207),
  ((SELECT id FROM tags WHERE slug='horse'), 207),
  ((SELECT id FROM tags WHERE slug='cow'), 207),
  ((SELECT id FROM tags WHERE slug='sheep'), 207),
  ((SELECT id FROM tags WHERE slug='monkey'), 207),
  ((SELECT id FROM tags WHERE slug='wolf'), 207),
  ((SELECT id FROM tags WHERE slug='panda'), 207),
  ((SELECT id FROM tags WHERE slug='whale'), 207),
  ((SELECT id FROM tags WHERE slug='dolphin'), 207),
  ((SELECT id FROM tags WHERE slug='butterfly'), 207),

  -- 野鳥 (208): bird 系は 207 + 208 の二重所属
  ((SELECT id FROM tags WHERE slug='bird'), 207),
  ((SELECT id FROM tags WHERE slug='bird'), 208),
  ((SELECT id FROM tags WHERE slug='sparrow'), 207),
  ((SELECT id FROM tags WHERE slug='sparrow'), 208),
  ((SELECT id FROM tags WHERE slug='eagle'), 207),
  ((SELECT id FROM tags WHERE slug='eagle'), 208),
  ((SELECT id FROM tags WHERE slug='hawk'), 207),
  ((SELECT id FROM tags WHERE slug='hawk'), 208),
  ((SELECT id FROM tags WHERE slug='owl'), 207),
  ((SELECT id FROM tags WHERE slug='owl'), 208),
  ((SELECT id FROM tags WHERE slug='crow'), 207),
  ((SELECT id FROM tags WHERE slug='crow'), 208),
  ((SELECT id FROM tags WHERE slug='heron'), 207),
  ((SELECT id FROM tags WHERE slug='heron'), 208),
  ((SELECT id FROM tags WHERE slug='crane'), 207),
  ((SELECT id FROM tags WHERE slug='crane'), 208),
  ((SELECT id FROM tags WHERE slug='swan'), 207),
  ((SELECT id FROM tags WHERE slug='swan'), 208),
  ((SELECT id FROM tags WHERE slug='goose'), 207),
  ((SELECT id FROM tags WHERE slug='goose'), 208),
  ((SELECT id FROM tags WHERE slug='duck'), 207),
  ((SELECT id FROM tags WHERE slug='duck'), 208),
  ((SELECT id FROM tags WHERE slug='seagull'), 207),
  ((SELECT id FROM tags WHERE slug='seagull'), 208),
  ((SELECT id FROM tags WHERE slug='penguin'), 207),
  ((SELECT id FROM tags WHERE slug='penguin'), 208),
  ((SELECT id FROM tags WHERE slug='flamingo'), 207),
  ((SELECT id FROM tags WHERE slug='flamingo'), 208),
  ((SELECT id FROM tags WHERE slug='falcon'), 207),
  ((SELECT id FROM tags WHERE slug='falcon'), 208),
  ((SELECT id FROM tags WHERE slug='kingfisher'), 207),
  ((SELECT id FROM tags WHERE slug='kingfisher'), 208),

  -- 自動車 (209)
  ((SELECT id FROM tags WHERE slug='car'), 209),
  ((SELECT id FROM tags WHERE slug='vehicle'), 209),
  ((SELECT id FROM tags WHERE slug='sedan'), 209),
  ((SELECT id FROM tags WHERE slug='suv'), 209),
  ((SELECT id FROM tags WHERE slug='truck'), 209),
  ((SELECT id FROM tags WHERE slug='sports-car'), 209),
  ((SELECT id FROM tags WHERE slug='convertible'), 209),
  ((SELECT id FROM tags WHERE slug='bus'), 209),
  ((SELECT id FROM tags WHERE slug='taxi'), 209),
  ((SELECT id FROM tags WHERE slug='pickup-truck'), 209),

  -- バイク (210)
  ((SELECT id FROM tags WHERE slug='motorcycle'), 210),
  ((SELECT id FROM tags WHERE slug='scooter'), 210),
  ((SELECT id FROM tags WHERE slug='moped'), 210),

  -- 鉄道 (211)
  ((SELECT id FROM tags WHERE slug='train'), 211),
  ((SELECT id FROM tags WHERE slug='railway'), 211),
  ((SELECT id FROM tags WHERE slug='locomotive'), 211),
  ((SELECT id FROM tags WHERE slug='subway'), 211),
  ((SELECT id FROM tags WHERE slug='tram'), 211),
  ((SELECT id FROM tags WHERE slug='cable-car'), 211),
  ((SELECT id FROM tags WHERE slug='monorail'), 211),
  ((SELECT id FROM tags WHERE slug='bullet-train'), 211),

  -- 飛行機 (212)
  ((SELECT id FROM tags WHERE slug='aircraft'), 212),
  ((SELECT id FROM tags WHERE slug='airplane'), 212),
  ((SELECT id FROM tags WHERE slug='helicopter'), 212),
  ((SELECT id FROM tags WHERE slug='jet'), 212),
  ((SELECT id FROM tags WHERE slug='airliner'), 212),
  ((SELECT id FROM tags WHERE slug='glider'), 212),

  -- 星空 (213)
  ((SELECT id FROM tags WHERE slug='star'), 213),
  ((SELECT id FROM tags WHERE slug='night-sky'), 213),
  ((SELECT id FROM tags WHERE slug='milky-way'), 213),
  ((SELECT id FROM tags WHERE slug='galaxy'), 213),
  ((SELECT id FROM tags WHERE slug='constellation'), 213),
  ((SELECT id FROM tags WHERE slug='nebula'), 213),
  ((SELECT id FROM tags WHERE slug='astronomy'), 213),
  ((SELECT id FROM tags WHERE slug='aurora'), 213)
;
